steps:
  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'us-east5-docker.pkg.dev/local-pier-449315-t3/python-hello-world/hello-world:${SHORT_SHA}',
            '-t',
            'us-east5-docker.pkg.dev/local-pier-449315-t3/python-hello-world/hello-world:latest',
            '--cache-from',
            'us-east5-docker.pkg.dev/local-pier-449315-t3/python-hello-world/hello-world:latest',
            '.'
          ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east5-docker.pkg.dev/local-pier-449315-t3/python-hello-world/hello-world:${SHORT_SHA}']
  
  # Also push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east5-docker.pkg.dev/local-pier-449315-t3/python-hello-world/hello-world:latest']

  # Convert to Apptainer/SIF
  - name: 'ubuntu:22.04'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get install -y software-properties-common && \
        add-apt-repository -y ppa:apptainer/ppa && \
        apt-get update && \
        apt-get install -y apptainer-suid && \
        apptainer build /workspace/hello-world.sif \
          docker://us-east5-docker.pkg.dev/local-pier-449315-t3/python-hello-world/hello-world:${SHORT_SHA}

# Store Docker images in Docker repository
images:
  - us-east5-docker.pkg.dev/local-pier-449315-t3/python-hello-world/hello-world:${SHORT_SHA}
  - us-east5-docker.pkg.dev/local-pier-449315-t3/python-hello-world/hello-world:latest

# Store SIF files in Generic repository
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'artifacts'
    - 'generic'
    - 'upload'
    - '--location=us-east5'
    - '--repository=python-hello-world-sif'
    - '--source=/workspace/hello-world.sif'
    - '--package=hello-world'
    - '--version=${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
